### ISSUE TITLE
Parallel option limits?

### ISSUE THREAD

**Issue by devinus** [wdavidw/node-stream-transform#8] opened 2015-03-25 17:29 UTC
I'm attempting to use `{ parallel: 5 }`, but that makes my pipeline only consume 5 lines rather than consumer 5 at a time. Is there something I'm missing?

**Comment by devinus** [comment] 2015-03-25 18:01
I believe this is because I'm returning an error in the transform, i.e. `callback(new Error())`. Should this stop the streaming?

**Comment by devinus** [comment] 2015-03-25 18:02
Also, if I use `callback(null, true);` it will only read 20 lines.

**Comment by wdavidw** [comment] 2015-03-26 13:28
yes, return a error will stop calling new callbacks

**Comment by wdavidw** [comment] 2015-03-26 13:31
... this might be wrong, some people have reported bugs that i couldnt reproduce. send me sample a sample reproducing the pb and i will look at it.

**Comment by wdavidw** [comment] 2015-10-20 20:45
You were probably not consuming the stream. See the new "consume" option if you still have issue and open a new issue with a sample or test case reproducing your issue. closing for now.

**Closed by wdavidw** 2015-10-20 20:45 UTC
